apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.configname}} 
data:
{{- with .Values.data }}
  ENVIRONMENT: {{.env | quote}}
  HOST: {{.host | quote}}
  PORT: {{.port | quote}}
  REDIS_HOST: {{.redishost | quote}}
  REDIS_PORT: {{.redisport | quote}}
  REDIS_DB: {{.redisdb | quote}}
{{- end }}