apiVersion: v1
kind: Service
metadata:
  name: {{.Values.servicename}}
  labels: 
    app: {{.Values.servicelabels.app}}
    tier: {{.Values.servicelabels.tier}}
spec:
  type: {{.Values.servicetype}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.servicetPort}}
  selector:
    app: {{.Values.servicelabels.app}}
    tier: {{.Values.servicelabels.tier}}